services:
    # database
    database:
        image: postgres
        container_name: database
        environment:
            POSTGRES_USER: ${POSTGRES_USER}
            POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
            POSTGRES_DB: ${POSTGRES_DB}
        ports:
            - '5432:5432'
        volumes:
            - postgres_data:/var/lib/postgresql
        networks:
            - weather-network

    # server / api
    server:
        build:
            context: ./server
            dockerfile: Dockerfile
        container_name: server
        environment:
            - ConnectionStrings__DefaultConnection=Host=database;Port=${POSTGRES_PORT};Database=${POSTGRES_DB};Username=${POSTGRES_USER};Password=${POSTGRES_PASSWORD}
            - ASPNETCORE_ENVIRONMENT=${ASPNETCORE_ENVIRONMENT}
            - JwtSettings__Secret=${JWT_SECRET}
            - WeatherApi__Key=${OPEN_WEATHET_API_KEY}
        ports:
            - '5001:8080'
        depends_on:
            - database
        networks:
            - weather-network

    # frontend
    client:
        build:
            context: ./client
            dockerfile: Dockerfile
        container_name: client
        ports:
            - '3000:80'
        depends_on:
            - server
        networks:
            - weather-network

# volumes
volumes:
    postgres_data:

# networks
networks:
    weather-network:
        driver: bridge
