services:
  # database
  db:
    image: postgres
    container_name: weather_db
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql
    networks:
      - weather-network

  # server / api
  api:
    build: 
      context: ./backend
      dockerfile: Dockerfile
    container_name: weather_api
    environment:
      - ConnectionStrings__DefaultConnection=Host=db;Port=${POSTGRES_PORT};Database=${POSTGRES_DB};Username=${POSTGRES_USER};Password=${POSTGRES_PASSWORD}
      - ASPNETCORE_ENVIRONMENT=${ASPNETCORE_ENVIRONMENT}
      - JwtSettings__Secret=${JWT_SECRET}
    ports:
      - "5001:8080"
    depends_on:
      - db
    networks:
      - weather-network

  # frontend
  web:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: weather_web
    ports:
      - "3000:80"
    depends_on:
      - api
    networks:
      - weather-network

# volumes
volumes:
  postgres_data:

# networks
networks:
  weather-network:
    driver: bridge